### ISSUE TITLE
Need to package pop-launcher and add to cosmic-launcher rundeps

### ISSUE THREAD

**Issue by Solarunit** [serpent-os/lichen#8]
Cosmic-launcher doesn't work in pa0.

>I haven't checked the logs but I had *assumed* cosmic-launcher built pop-os-launcher into it 
>I suspect it cals it via IPC
>And needs the other launcher thingy packaged

PS: posting in lichen repo as I am not sure what is a proper repo to report

**Comment by Lyamc** [comment]
@Solarunit pretty sure it needs to be in here: https://github.com/snekpit/main

**Comment by ikeycode** [comment]
Nowadays its in `serpent-os/recipes`, need to deprecate `snekpit` sorry! But yeah I've added pop-os-launcher and its currently a bit broken

**Comment by ikeycode** [comment]
Fixed a while ago, will be present in next iso properly ^^
